### ISSUE TITLE
Let's start 

### ISSUE THREAD

**Issue by AliWayDev** [khaledxyz/Valkyrie#3]
Hi,
"How can I help you ?",
so I like your project but I don't understand many things there,
can you share the design of this project? maybe so I will understand it.

And can you just tell me about the goals of this project?

Thank you //

**Comment by khaledhalloua** [comment]
Hello!

Thanks for reaching out Ali Nurlibekov. So the project is basically a [Discord ](https://discord.com/) clone (I'm planning to include only the core features). I don't have a design because I'm not a designer. I'm copying Discord's UI; Though I have a different color palette than theirs: 
See `client/src/sass/utils/variables.scss`. Since this is my first fullstack mern project; things all over the place so I appologize about that.

**The core featuers are:**

- Login/Sign Up (Done) `[Routes : /login / signup]`
- DMs & friend requests
- Creating Servers (Almost done) [Referred to as Guilds in the source code to avoid any confusion with the 'server' of the app]
- Inviting Friends to Servers

**Main technologies:**

- MongoDB (Mongoose)
- ExpressJS
- React (Vite)
- Socket.IO

After I'm done with most of these I'm planning to add voice chats & video chats.

I'm currently working on the UI of the dashboard `[See: http://localhost:{PORT}/channels]`. And I'll try to include more info in the readme later on.

**Comment by AliWayDev** [comment]
Okay, I understand and I'm waiting for the issues.
